# NUMPY

In [ ]:
import numpy as np

In [2]:
np_height = np.array([1.5,1.6,1.7,1.8])

In [3]:
np_weight = np.array([70,73,74,80])

In [4]:
bmi = np_height/np_weight**2

In [5]:
bmi

array([ 0.00030612,  0.00030024,  0.00031045,  0.00028125])

Numpy array only works with elements of the same type

In [6]:
[1.5,1.6,1.7,1.8]+[70,73,74,80]

[1.5, 1.6, 1.7, 1.8, 70, 73, 74, 80]

In [7]:
np_height + np_weight

array([ 71.5,  74.6,  75.7,  81.8])

In [8]:
bmi[1]

0.00030024394820791893

In [9]:
bmi > 0.0000001

array([ True,  True,  True,  True], dtype=bool)

In [10]:
bmi[bmi>0.0000001]

array([ 0.00030612,  0.00030024,  0.00031045,  0.00028125])

In [11]:
np_height_m = np_height * 0.0254

In [12]:
print(np_height_m)

[ 0.0381   0.04064  0.04318  0.04572]


In [1]:
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

In [4]:
# Create a 2D Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball, numero righe x numero colonne
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [7]:
# Print out the 1st row of np_baseball
print(np_baseball[0])

# Select the entire second column of np_baseball: np_weight
np_weight = np_baseball[:,1]

# Print out height of 3th player
print(np_baseball[3,0])

[ 180.    78.4]
188.0


In [9]:
conversion = [0.0254, 0.453592]
np_baseball_converted = np_baseball * conversion
print(np_baseball_converted)

[[  4.572      35.5616128]
 [  5.461      46.5838984]
 [  5.334      44.678812 ]
 [  4.7752     34.1101184]]


In [10]:
np.round(np.random.normal(10,30,100)) #mean sd number of terms

array([  -8.,   59.,   25.,    9.,   41.,    3.,   22.,   46.,   24.,
         32.,   44.,   25.,   45.,  101.,  -19.,   28.,    4.,  -39.,
         50.,  -11.,   14.,    6.,   56.,    5.,   32.,  -12.,   48.,
        -18.,  -15.,  -25.,  -43.,   36.,  -23.,   43.,  -41.,   31.,
         62.,   44.,  -19.,   15.,   67.,   23.,   13.,   29.,   -9.,
         77.,   19.,  -13.,  -23.,   23.,    5.,  -18.,    6.,   40.,
         67.,    8.,   50.,   -9.,   -8.,   25.,   22.,   52.,  -13.,
         60.,  -15.,   33.,   15.,   17.,    4.,   54.,   18.,   -7.,
         -4.,    3.,   11.,   20.,   -7.,   19.,  -23.,   41.,   15.,
         34.,   71.,   26.,    2.,  -57.,    3.,   33.,   13.,   74.,
         15.,    9.,    4.,  -12.,   34.,  -37.,  -11.,  -25.,   20.,  -25.])

In [11]:
# Create np_height from np_baseball
np_height = np_baseball[:,0]

# Print out the mean of np_height
print(np.mean(np_height))

# Print out the median of np_height
print(np.median(np_height))

198.25
199.0


In [14]:
# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.6351460533
Correlation: [[ 1.          0.95865738]
 [ 0.95865738  1.        ]]
